name = "Practiv Docs"
license = ""
licenselink = ""
description = "Practiv public documentation"
homepage = "https://docstest.vercel.app/"
tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = ""
  homepage = ""
